#!/usr/bin/env python3
"""Organization Profile README Generator v3"""
import json, os, sys, urllib.request, urllib.error
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
CONFIG_PATH = REPO_ROOT.parent / "brand.config.json"
CACHE_PATH = REPO_ROOT / ".github" / "repo-state.json"
README_PATH = REPO_ROOT / "profile" / "README.md"
API_BASE = "https://api.github.com"
ORG = "dhaher-labs"

def load_config():
    try: return json.loads(CONFIG_PATH.read_text())
    except: return {}

def api_get(path, token=None):
    url = f"{API_BASE}{path}"
    headers = {"User-Agent": "dhaher-brand-gen", "Accept": "application/vnd.github.v3+json"}
    if token: headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as r: return json.loads(r.read().decode())
    except: return []

def fetch_all_repos(org, token=None):
    repos, page = [], 1
    while True:
        path = f"/orgs/{org}/repos?per_page=100&page={page}&sort=updated&direction=desc"
        batch = api_get(path, token)
        if not batch: break
        repos.extend(batch)
        if len(batch) < 100: break
        page += 1
    return repos

def load_cache():
    try: return json.loads(CACHE_PATH.read_text())
    except: return {"lastSync": None, "repos": []}

def save_cache(state):
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_text(json.dumps(state, indent=2))

def normalize(r):
    return {"name": r.get("name",""), "description": r.get("description") or "", "stars": r.get("stargazers_count",0), "forks": r.get("forks_count",0), "language": r.get("language"), "url": r.get("html_url",""), "isPrivate": r.get("private",False), "isFork": r.get("fork",False), "updatedAt": r.get("updated_at"), "topics": r.get("topics",[])}

def detect_changes(cached, current):
    cm = {r["name"].lower(): r for r in cached}
    nm = {r["name"].lower(): r for r in current}
    added = [r for n,r in nm.items() if n not in cm]
    removed = [r for n,r in cm.items() if n not in nm]
    modified = [r for n,r in nm.items() if n in cm and (cm[n].get("stars")!=r.get("stars") or cm[n].get("description")!=r.get("description"))]
    return added, removed, modified, bool(added or removed or modified)

def build_readme(config, featured, public, ts):
    contact = config.get("contact", {})
    brand = config.get("brand", {})

    def repo_rows(repos):
        if not repos: return "_No repos found._"
        rows = ["| Repository | Description | Tech |", "|------------|-------------|------|"]
        for r in repos:
            lang = r.get("language") or "—"
            desc = (r.get("description") or "—")[:55]
            rows.append(f"| [`{r['name']}`]({r['url']}) | {desc} | {lang} |")
        return "\n".join(rows)

    return f"""<!-- AUTO-GENERATED — Do not edit manually. Regenerated by sync workflow. -->
<!-- Last updated: {ts} -->

<div align="center">

<img width="100%" src="assets/banner.png" alt="Dhaher Labs — Banner" />
<br/>
<img width="72" src="assets/logo.png" alt="Dhaher Labs Logo" style="margin-top:-10px;" />
<br/>
<h1><span style="color:#FFFFFF;">DHAHER</span> <span style="color:#D9A441;">LABS</span></h1>
<p style="color:#00D1C7;">AI &bull; Quantitative Intelligence &bull; Autonomous Workflows &bull; Open-Source Research</p>
<p style="color:#8B949E;">{brand.get("description","")}</p>

</div>

---

### `// mission`

> *We build tools, not hype. Practical systems, not promises.*

{brand.get("description","")}

Currently being built by [Mulky Malikul Dhaher](https://github.com/mulkymalikuldhaher).

---

### Focus Areas

<table>
<tr>
<td width="25%" align="center" style="background:#1A1D20;"><br/><img src="https://img.shields.io/badge/AI_SYSTEMS-00D1C7?style=for-the-badge&labelColor=1A1D20" /><br/><br/><p style="color:#8B949E;font-size:0.85rem;">LLM integration, multi-agent coordination</p><br/></td>
<td width="25%" align="center" style="background:#1A1D20;"><br/><img src="https://img.shields.io/badge/QUANT_INTELLIGENCE-D9A441?style=for-the-badge&labelColor=1A1D20" /><br/><br/><p style="color:#8B949E;font-size:0.85rem;">Data pipelines, models, research dashboards</p><br/></td>
<td width="25%" align="center" style="background:#1A1D20;"><br/><img src="https://img.shields.io/badge/AUTONOMOUS_WORKFLOWS-00D1C7?style=for-the-badge&labelColor=1A1D20" /><br/><br/><p style="color:#8B949E;font-size:0.85rem;">Automation, orchestration, agent systems</p><br/></td>
<td width="25%" align="center" style="background:#1A1D20;"><br/><img src="https://img.shields.io/badge/OPEN_SOURCE-D9A441?style=for-the-badge&labelColor=1A1D20" /><br/><br/><p style="color:#8B949E;font-size:0.85rem;">Transparency, community, real tools</p><br/></td>
</tr>
</table>

---

### Featured Repositories

{repo_rows(featured)}

---

### All Public Repositories

{repo_rows(public[:20])}

---

### What We Build

- **Practical** — Solves a real problem, not just a demo
- **Open** — Source available, decisions documented
- **Composable** — Fits into a larger system
- **Honest** — No overclaimed intelligence or fake autonomy

---

### Contact

```
Email:      {contact.get("email","")}
Instagram:  {contact.get("instagram","")}
GitHub:     github.com/dhaher-labs
Builder:    github.com/mulkymalikuldhaher
```

<div align="center"><em>Research &bull; Build &bull; Automate &bull; Ship</em></div>
"""

def main():
    token = os.environ.get("GITHUB_TOKEN", "")
    ts = datetime.now(timezone.utc).isoformat()
    config = load_config()
    print(f"🚀 Org README Gen | {ORG} | {ts}")

    raw = fetch_all_repos(ORG, token)
    all_repos = [normalize(r) for r in raw]
    print(f"   Found {len(all_repos)} repos")

    featured_names = set(p["name"].lower() for p in config.get("projects",{}).get("featured",[]))
    featured = [r for r in all_repos if r["name"].lower() in featured_names]
    public = sorted([r for r in all_repos if not r["isPrivate"] and not r["isFork"]], key=lambda r: (-r["stars"], r.get("updatedAt") or ""))

    cache = load_cache()
    added, removed, modified, has = detect_changes(cache.get("repos",[]), all_repos)
    if has: print(f"🔄 Changes: +{len(added)} -{len(removed)} ~{len(modified)}")

    readme = build_readme(config, featured, public, ts)
    README_PATH.parent.mkdir(parents=True, exist_ok=True)
    README_PATH.write_text(readme)
    save_cache({"lastSync": ts, "repos": all_repos})
    print(f"📝 Written to {README_PATH}")

if __name__ == "__main__":
    main()
